apiVersion: v1
kind: Service
metadata:
    name: "aksgithubcicd-62c5"
    labels:
        app: "aksgithubcicd-62c5"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksgithubcicd-62c5"