apiVersion: v1
kind: Service
metadata:
    name: "aksgithubcicd-c702"
    labels:
        app: "aksgithubcicd-c702"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksgithubcicd-c702"