version: '3.1'
services:
    db:
        build:
            context: ./mysql/
            dockerfile: Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        restart: always