on: [pull_request]
env: 
  NAMESPACE: production
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrgithubcicd.azurecr.io
        username: ${{ secrets.acr_acrgithubcicd_username }}
        password: ${{ secrets.acr_acrgithubcicd_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/src/php" -f  "src/php/Dockerfile" -t acrgithubcicd.azurecr.io/aksgithubcicd:${{ github.sha }}-php --label dockerfile-path=src/php/Dockerfile
        docker push acrgithubcicd.azurecr.io/aksgithubcicd:${{ github.sha }}-php
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksgithubcicd_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ${{ env.NAMESPACE  }} | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ${{ env.NAMESPACE  }}`
        fi
        namespaceAkvPresent=`kubectl get namespace | grep akv2k8s | wc -l`
        if [ $namespaceAkvPresent -eq 0 ]
        then
            echo `kubectl create namespace akv2k8s`
            echo `helm repo add spv-charts https://charts.spvapi.no`
            echo `helm repo update`
            echo `helm upgrade --install akv2k8s spv-charts/akv2k8s --namespace akv2k8s`
        fi     

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ${{ env.NAMESPACE  }}
        container-registry-url: acrgithubcicd.azurecr.io
        container-registry-username: ${{ secrets.acr_acrgithubcicd_username }}
        container-registry-password: ${{ secrets.acr_acrgithubcicd_password }}
        secret-name: aksgithubcicdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ${{ env.NAMESPACE  }}
        manifests: |
          manifests/phpproductionsecret.yaml
          manifests/secret-sync.yaml
          manifests/phpdeploy.yaml
          manifests/phpservice.yaml
        images: |
          acrgithubcicd.azurecr.io/aksgithubcicd:${{ github.sha }}-php
        imagepullsecrets: |
          aksgithubcicdockerauth
