on: [push]
env: 
  NAMESPACE: staging
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrgithubcicd.azurecr.io
        username: ${{ secrets.acr_acrgithubcicd_username }}
        password: ${{ secrets.acr_acrgithubcicd_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/src/mysql" -f  "src/mysql/Dockerfile" -t acrgithubcicd.azurecr.io/aksgithubcicd:${{ github.sha }}-mysql --label dockerfile-path=src/mysql/Dockerfile
        docker push acrgithubcicd.azurecr.io/aksgithubcicd:${{ github.sha }}-mysql
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksgithubcicd_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ${{ env.NAMESPACE  }} | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ${{ env.NAMESPACE  }}`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ${{ env.NAMESPACE  }}
        container-registry-url: acrgithubcicd.azurecr.io
        container-registry-username: ${{ secrets.acr_acrgithubcicd_username }}
        container-registry-password: ${{ secrets.acr_acrgithubcicd_password }}
        secret-name: aksgithubcicdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ${{ env.NAMESPACE  }}
        manifests: |
          manifests/mysqlsecret.yaml
          manifests/mysqlset.yaml
          manifests/mysqlservice.yaml
        images: |
          acrgithubcicd.azurecr.io/aksgithubcicd:${{ github.sha }}-mysql
        imagepullsecrets: |
          aksgithubcicdockerauth
